version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0 && flask create_db
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    ports:
      - 5432:5432
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass random
    volumes:
      - cache:/data
volumes:
  postgres_data:
  cache:
    driver: local
